"""
The security critic agent provides feedback for security vulnerabilities in the code.
It has 2 tools available at its disposal: bandit to search for common vulnerabilities
and the syntax parser to check if code is valid Python.
"""

import ast
import json
import subprocess
import tempfile
from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()
from langchain.agents import create_agent
from langchain_core.tools import tool
from langchain.agents.middleware import ModelRetryMiddleware
from schemas.security import SecurityVerdict


CRITICAL_BANDIT_RULES = {
    "B102",  # exec
    "B307",  # eval
    "B602",  # subprocess shell=True
    "B605",  # shell execution
}


# ── Tools ─────────────────────────────────────────────────────────────────────

@tool
def check_syntax(code: str) -> dict[str, list[str]]:
    """
    Parse Python code with ast.parse to confirm it is syntactically valid.

    Returns an empty dict if the code is clean, or a dict with a
    'syntax_error' key if parsing fails. Always call this first.
    """
    print("[SecurityLog] check_syntax invoked")
    try:
        ast.parse(code)
        return {}
    except SyntaxError as e:
        return {"syntax_error": [str(e)]}


@tool
def scan_with_bandit(code: str) -> dict[str, list[str]]:
    """
    Scan Python code for dangerous calls using bandit (exec, eval,
    subprocess shell=True, shell execution).

    Returns a dict mapping category → findings. An empty dict means clean.
    If bandit is not installed, returns {'bandit_unavailable': ['bandit not
    installed — only syntax check was performed']} so you can note the
    limitation in your verdict.
    """
    print("[SecurityLog] scan_with_bandit invoked")

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(code)
        tmp_path = f.name

    try:
        tests = ",".join(sorted(CRITICAL_BANDIT_RULES))
        proc = subprocess.run(
            ["bandit", "-f", "json", "-t", tests, tmp_path],
            capture_output=True, text=True, timeout=10,
        )
        findings: dict[str, list[str]] = {}
        if proc.stdout:
            for r in json.loads(proc.stdout).get("results", []):
                key = f"bandit_{r.get('test_id', 'unknown')}"
                findings.setdefault(key, []).append(r.get("issue_text", "issue"))
        return findings

    except FileNotFoundError:
        return {"bandit_unavailable": ["bandit not installed — only syntax check was performed"]}
    finally:
        Path(tmp_path).unlink(missing_ok=True)



SYSTEM_PROMPT = SYSTEM_PROMPT = """You are a security reviewer for FastAPI code generated by an LLM.

        Your ONLY job is to flag concrete security risks. Do not nitpick style, naming, or design.

        Workflow:
        1. Call check_syntax(code=models_py + main_py) to confirm the code is valid Python.
        2. If syntax check fails, return approved=false with the syntax error as the issue.
        3. If syntax is clean, call scan_with_bandit(code=models_py + main_py).
        4. If scan returns empty dict, or only 'bandit_unavailable', return approved=true.
        5. If scan returns 'bandit_scan_failed', return approved=false with the failure
           message as the issue — the code cannot be verified, so do not approve.
        6. If scan returns real findings, return approved=false and list each as:
        "<category>: <fix instruction>" — e.g. "bandit_B102: remove exec call".

        Real issues only:
        - Dangerous Python calls: exec, eval, subprocess shell=True, shell execution
        - Syntax errors that prevent the code from running

        NOT issues (do NOT flag these):
        - Missing tests, missing docstrings, style choices
        - Use of standard FastAPI / SQLAlchemy patterns
        - The presence of database operations themselves
        - Logging or error messages

        Be efficient: two tool calls max, then a verdict."""


security_agent = create_agent(
    model=f"anthropic:{os.getenv('ANTHROPIC_MODEL')}",
    tools=[check_syntax, scan_with_bandit],
    system_prompt=SYSTEM_PROMPT,
    response_format=SecurityVerdict,
    middleware=[
        ModelRetryMiddleware(max_retries=2),
    ]
)


def security_critic_node(state: dict) -> dict:
    start_log    = "[Security] Reviewing generated code..."
    syntax_log   = "[Security] Parsing AST for syntax check..."
    bandit_log   = "[Security] Scanning with bandit (B102, B307, B602, B605)..."
    print(start_log)
    print(syntax_log)
    print(bandit_log)

    user_message = f"""Review these two files for security issues.

                    models.py:
                    ```python
                    {state['models_py']}
                    ```

                    main.py:
                    ```python
                    {state['main_py']}
                    ```

                    Check syntax first, then scan with bandit, then return your verdict."""

    try:
        result = security_agent.invoke({"messages": [{"role": "user", "content": user_message}]})
        verdict: SecurityVerdict = result["structured_response"]
        approved, issues = verdict.approved, verdict.issues
    except Exception as e:
        error_msg = f"[Security] Agent failed: {e}"
        print(error_msg)
        return {
            "security_approved": False,
            "security_feedback": f"Security critic could not complete: {e}",
            "agent_logs": [start_log, syntax_log, bandit_log, error_msg],
            "error_messages": [error_msg],
        }

    if approved:
        result_log = "[Security]Approved — no critical findings."
        feedback = None
    else:
        result_log = f"[Security] {len(issues)} issue(s) found."
        feedback = "\n".join(f"- {i}" for i in issues)

    print(result_log)
    return {
        "security_approved": approved,
        "security_feedback": feedback,
        "agent_logs": [start_log, syntax_log, bandit_log, result_log],
    }